-- MySQL Script generated by MySQL Workbench
-- Sat Apr 30 12:35:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema m193241
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema m193241
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `m193241` DEFAULT CHARACTER SET utf8 ;
USE `m193241` ;

-- -----------------------------------------------------
-- Table `m193241`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m193241`.`players` (
  `id_p` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_p`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m193241`.`weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m193241`.`weapons` (
  `id_w` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_w`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m193241`.`skins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m193241`.`skins` (
  `id_s` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `quality` VARCHAR(45) NULL,
  PRIMARY KEY (`id_s`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m193241`.`players_has_weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m193241`.`players_has_weapons` (
  `players_id_p` INT UNSIGNED NOT NULL,
  `weapons_id_w` INT NOT NULL,
  PRIMARY KEY (`players_id_p`, `weapons_id_w`),
  INDEX `fk_players_has_weapons_weapons1_idx` (`weapons_id_w` ASC) VISIBLE,
  INDEX `fk_players_has_weapons_players_idx` (`players_id_p` ASC) VISIBLE,
  CONSTRAINT `fk_players_has_weapons_players`
    FOREIGN KEY (`players_id_p`)
    REFERENCES `m193241`.`players` (`id_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_has_weapons_weapons1`
    FOREIGN KEY (`weapons_id_w`)
    REFERENCES `m193241`.`weapons` (`id_w`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m193241`.`weapons_has_skins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m193241`.`weapons_has_skins` (
  `weapons_id_w` INT NOT NULL,
  `skins_id_s` INT NOT NULL,
  PRIMARY KEY (`weapons_id_w`, `skins_id_s`),
  INDEX `fk_weapons_has_skins_skins1_idx` (`skins_id_s` ASC) VISIBLE,
  INDEX `fk_weapons_has_skins_weapons1_idx` (`weapons_id_w` ASC) VISIBLE,
  CONSTRAINT `fk_weapons_has_skins_weapons1`
    FOREIGN KEY (`weapons_id_w`)
    REFERENCES `m193241`.`weapons` (`id_w`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_weapons_has_skins_skins1`
    FOREIGN KEY (`skins_id_s`)
    REFERENCES `m193241`.`skins` (`id_s`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `m193241`.`players`
-- -----------------------------------------------------
START TRANSACTION;
USE `m193241`;
INSERT INTO `m193241`.`players` (`id_p`, `nickname`, `email`) VALUES (1, 'Lojza Kadrnoška', NULL);
INSERT INTO `m193241`.`players` (`id_p`, `nickname`, `email`) VALUES (2, 'Gamer123', NULL);
INSERT INTO `m193241`.`players` (`id_p`, `nickname`, `email`) VALUES (3, 'TopFragger', NULL);
INSERT INTO `m193241`.`players` (`id_p`, `nickname`, `email`) VALUES (4, 'HeadshotMaster', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `m193241`.`weapons`
-- -----------------------------------------------------
START TRANSACTION;
USE `m193241`;
INSERT INTO `m193241`.`weapons` (`id_w`, `name`) VALUES (1, 'AK47');
INSERT INTO `m193241`.`weapons` (`id_w`, `name`) VALUES (2, 'M4A4');
INSERT INTO `m193241`.`weapons` (`id_w`, `name`) VALUES (3, 'M4A1-S');
INSERT INTO `m193241`.`weapons` (`id_w`, `name`) VALUES (4, 'AWP');
INSERT INTO `m193241`.`weapons` (`id_w`, `name`) VALUES (5, 'Desert Eagle');
INSERT INTO `m193241`.`weapons` (`id_w`, `name`) VALUES (6, 'USP-S');
INSERT INTO `m193241`.`weapons` (`id_w`, `name`) VALUES (7, 'Glock-18');

COMMIT;


-- -----------------------------------------------------
-- Data for table `m193241`.`skins`
-- -----------------------------------------------------
START TRANSACTION;
USE `m193241`;
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (1, 'Asiimov', 450, 'Factory New');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (3, 'Wasteland Rebel', 200, 'Minimal Wear');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (4, 'Wildfire', 300, 'Well-Worn');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (6, 'Fade', 1000, 'Factory New');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (7, 'Redline', 150, 'Battle-Scared');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (8, 'Black Lotus', 100, 'Field-Tested');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (9, 'Cortex', 150, 'Well-Worn');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (10, 'Cyrex', 75, 'Battle-Scared');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (11, 'Printstream', 450, 'Minimal Wear');
INSERT INTO `m193241`.`skins` (`id_s`, `name`, `price`, `quality`) VALUES (12, 'Moonrise', 125, 'Factory New');

COMMIT;

